# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tpaurlui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TpaUrlui(object):
    def setupUi(self, TpaUrlui):
        TpaUrlui.setObjectName("TpaUrlui")
        TpaUrlui.resize(1091, 553)
        self.centralWidget = QtWidgets.QWidget(TpaUrlui)
        self.centralWidget.setObjectName("centralWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(820, 270, 142, 92))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_filetype = QtWidgets.QLabel(self.layoutWidget)
        self.label_filetype.setObjectName("label_filetype")
        self.gridLayout_2.addWidget(self.label_filetype, 0, 0, 1, 1)
        self.comboBox_filetype = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_filetype.setObjectName("comboBox_filetype")
        self.comboBox_filetype.addItem("")
        self.comboBox_filetype.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_filetype, 0, 1, 1, 1)
        self.label_filename = QtWidgets.QLabel(self.layoutWidget)
        self.label_filename.setObjectName("label_filename")
        self.gridLayout_2.addWidget(self.label_filename, 1, 0, 1, 1)
        self.comboBox_filename = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_filename.setObjectName("comboBox_filename")
        self.comboBox_filename.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_filename, 1, 1, 1, 1)
        self.comboBox_srchtmclass = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_srchtmclass.setObjectName("comboBox_srchtmclass")
        self.comboBox_srchtmclass.addItem("")
        self.comboBox_srchtmclass.addItem("")
        self.comboBox_srchtmclass.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_srchtmclass, 2, 1, 1, 1)
        self.label_srchtmclass = QtWidgets.QLabel(self.layoutWidget)
        self.label_srchtmclass.setObjectName("label_srchtmclass")
        self.gridLayout_2.addWidget(self.label_srchtmclass, 2, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(620, 380, 341, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_filesize = QtWidgets.QLabel(self.layoutWidget1)
        self.label_filesize.setObjectName("label_filesize")
        self.gridLayout_3.addWidget(self.label_filesize, 0, 0, 1, 1)
        self.lineEdit_filesize = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_filesize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_filesize.setObjectName("lineEdit_filesize")
        self.gridLayout_3.addWidget(self.lineEdit_filesize, 0, 1, 1, 1)
        self.label_oldstr = QtWidgets.QLabel(self.layoutWidget1)
        self.label_oldstr.setObjectName("label_oldstr")
        self.gridLayout_3.addWidget(self.label_oldstr, 1, 0, 1, 1)
        self.lineEdit_oldstr = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_oldstr.setObjectName("lineEdit_oldstr")
        self.gridLayout_3.addWidget(self.lineEdit_oldstr, 1, 1, 1, 1)
        self.label_newstr = QtWidgets.QLabel(self.layoutWidget1)
        self.label_newstr.setObjectName("label_newstr")
        self.gridLayout_3.addWidget(self.label_newstr, 2, 0, 1, 1)
        self.lineEdit_newstr = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_newstr.setObjectName("lineEdit_newstr")
        self.gridLayout_3.addWidget(self.lineEdit_newstr, 2, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 951, 241))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_url = QtWidgets.QLabel(self.layoutWidget2)
        self.label_url.setObjectName("label_url")
        self.gridLayout.addWidget(self.label_url, 0, 0, 1, 1)
        self.lineEdit_url = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_url.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_url.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_url.setText("")
        self.lineEdit_url.setClearButtonEnabled(False)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.gridLayout.addWidget(self.lineEdit_url, 0, 1, 1, 1)
        self.label_type = QtWidgets.QLabel(self.layoutWidget2)
        self.label_type.setObjectName("label_type")
        self.gridLayout.addWidget(self.label_type, 1, 0, 1, 1)
        self.lineEdit_type = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_type.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_type.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_type.setClearButtonEnabled(False)
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.gridLayout.addWidget(self.lineEdit_type, 1, 1, 1, 1)
        self.label_htmlpath = QtWidgets.QLabel(self.layoutWidget2)
        self.label_htmlpath.setObjectName("label_htmlpath")
        self.gridLayout.addWidget(self.label_htmlpath, 2, 0, 1, 1)
        self.lineEdit_htmlpath = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_htmlpath.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_htmlpath.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_htmlpath.setObjectName("lineEdit_htmlpath")
        self.gridLayout.addWidget(self.lineEdit_htmlpath, 2, 1, 1, 1)
        self.label_baseurl = QtWidgets.QLabel(self.layoutWidget2)
        self.label_baseurl.setObjectName("label_baseurl")
        self.gridLayout.addWidget(self.label_baseurl, 3, 0, 1, 1)
        self.lineEdit_baseurl = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_baseurl.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_baseurl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_baseurl.setObjectName("lineEdit_baseurl")
        self.gridLayout.addWidget(self.lineEdit_baseurl, 3, 1, 1, 1)
        self.label_filepath = QtWidgets.QLabel(self.layoutWidget2)
        self.label_filepath.setObjectName("label_filepath")
        self.gridLayout.addWidget(self.label_filepath, 4, 0, 1, 1)
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_filepath.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_filepath.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.gridLayout.addWidget(self.lineEdit_filepath, 4, 1, 1, 1)
        self.label_times = QtWidgets.QLabel(self.layoutWidget2)
        self.label_times.setObjectName("label_times")
        self.gridLayout.addWidget(self.label_times, 5, 0, 1, 1)
        self.lineEdit_times = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_times.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_times.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_times.setObjectName("lineEdit_times")
        self.gridLayout.addWidget(self.lineEdit_times, 5, 1, 1, 1)
        self.label_nextstr = QtWidgets.QLabel(self.layoutWidget2)
        self.label_nextstr.setObjectName("label_nextstr")
        self.gridLayout.addWidget(self.label_nextstr, 6, 0, 1, 1)
        self.lineEdit_nextstr = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_nextstr.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_nextstr.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_nextstr.setText("")
        self.lineEdit_nextstr.setObjectName("lineEdit_nextstr")
        self.gridLayout.addWidget(self.lineEdit_nextstr, 6, 1, 1, 1)
        self.checkBox_nexttype = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_nexttype.setGeometry(QtCore.QRect(981, 219, 16, 16))
        self.checkBox_nexttype.setText("")
        self.checkBox_nexttype.setObjectName("checkBox_nexttype")
        self.comboBox_urltype = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_urltype.setGeometry(QtCore.QRect(980, 10, 50, 20))
        self.comboBox_urltype.setObjectName("comboBox_urltype")
        self.comboBox_urltype.addItem("")
        self.comboBox_urltype.addItem("")
        self.checkBox_open = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_open.setGeometry(QtCore.QRect(982, 121, 16, 16))
        self.checkBox_open.setText("")
        self.checkBox_open.setObjectName("checkBox_open")
        self.checkBox_next = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_next.setGeometry(QtCore.QRect(1001, 121, 16, 16))
        self.checkBox_next.setText("")
        self.checkBox_next.setObjectName("checkBox_next")
        self.checkBox_genLink = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_genLink.setGeometry(QtCore.QRect(980, 170, 16, 16))
        self.checkBox_genLink.setText("")
        self.checkBox_genLink.setObjectName("checkBox_genLink")
        self.label_genLink = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink.setGeometry(QtCore.QRect(980, 150, 81, 16))
        self.label_genLink.setObjectName("label_genLink")
        self.label_genLink_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink_2.setGeometry(QtCore.QRect(970, 390, 51, 16))
        self.label_genLink_2.setObjectName("label_genLink_2")
        self.label_genLink_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink_3.setGeometry(QtCore.QRect(980, 200, 91, 16))
        self.label_genLink_3.setObjectName("label_genLink_3")
        self.label_genLink_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink_4.setGeometry(QtCore.QRect(980, 100, 91, 16))
        self.label_genLink_4.setObjectName("label_genLink_4")
        self.pushButton_find = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_find.setGeometry(QtCore.QRect(519, 260, 75, 23))
        self.pushButton_find.setObjectName("pushButton_find")
        self.checkBox_folderorfile = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_folderorfile.setGeometry(QtCore.QRect(1030, 390, 16, 16))
        self.checkBox_folderorfile.setText("")
        self.checkBox_folderorfile.setObjectName("checkBox_folderorfile")
        self.pushButton_rmvoidfolder = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_rmvoidfolder.setGeometry(QtCore.QRect(970, 426, 91, 23))
        self.pushButton_rmvoidfolder.setObjectName("pushButton_rmvoidfolder")
        self.pushButton_renamefolder = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_renamefolder.setGeometry(QtCore.QRect(970, 470, 91, 23))
        self.pushButton_renamefolder.setObjectName("pushButton_renamefolder")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(981, 330, 75, 23))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_run = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_run.setGeometry(QtCore.QRect(981, 286, 75, 23))
        self.pushButton_run.setObjectName("pushButton_run")
        self.lineEdit_bspath = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_bspath.setGeometry(QtCore.QRect(100, 320, 401, 20))
        self.lineEdit_bspath.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_bspath.setObjectName("lineEdit_bspath")
        self.label_genLink_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink_6.setGeometry(QtCore.QRect(11, 320, 60, 16))
        self.label_genLink_6.setObjectName("label_genLink_6")
        self.lineEdit_htmlstr = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_htmlstr.setGeometry(QtCore.QRect(100, 260, 401, 20))
        self.lineEdit_htmlstr.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_htmlstr.setObjectName("lineEdit_htmlstr")
        self.label_genLink_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink_5.setGeometry(QtCore.QRect(11, 260, 72, 16))
        self.label_genLink_5.setObjectName("label_genLink_5")
        self.label_genLink_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink_7.setGeometry(QtCore.QRect(10, 290, 81, 20))
        self.label_genLink_7.setObjectName("label_genLink_7")
        self.lineEdit_classstr = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_classstr.setGeometry(QtCore.QRect(100, 290, 401, 20))
        self.lineEdit_classstr.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_classstr.setObjectName("lineEdit_classstr")
        self.label_genLink_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink_8.setGeometry(QtCore.QRect(10, 390, 71, 16))
        self.label_genLink_8.setObjectName("label_genLink_8")
        self.lineEdit_dbname = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_dbname.setGeometry(QtCore.QRect(99, 390, 401, 20))
        self.lineEdit_dbname.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_dbname.setObjectName("lineEdit_dbname")
        self.label_genLink_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink_9.setGeometry(QtCore.QRect(11, 420, 91, 16))
        self.label_genLink_9.setObjectName("label_genLink_9")
        self.lineEdit_collection = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_collection.setGeometry(QtCore.QRect(100, 420, 401, 20))
        self.lineEdit_collection.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_collection.setObjectName("lineEdit_collection")
        self.lineEdit_modbkey = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_modbkey.setGeometry(QtCore.QRect(99, 450, 401, 20))
        self.lineEdit_modbkey.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_modbkey.setObjectName("lineEdit_modbkey")
        self.label_genLink_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink_10.setGeometry(QtCore.QRect(10, 450, 91, 16))
        self.label_genLink_10.setObjectName("label_genLink_10")
        self.pushButton_writedb = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_writedb.setGeometry(QtCore.QRect(520, 390, 75, 23))
        self.pushButton_writedb.setObjectName("pushButton_writedb")
        self.comboBox_inserttype = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_inserttype.setGeometry(QtCore.QRect(100, 480, 91, 20))
        self.comboBox_inserttype.setObjectName("comboBox_inserttype")
        self.comboBox_inserttype.addItem("")
        self.comboBox_inserttype.addItem("")
        self.label_genLink_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink_11.setGeometry(QtCore.QRect(10, 480, 91, 16))
        self.label_genLink_11.setObjectName("label_genLink_11")
        self.label_genLink_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_genLink_12.setGeometry(QtCore.QRect(980, 240, 91, 16))
        self.label_genLink_12.setObjectName("label_genLink_12")
        self.checkBox_writelog = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_writelog.setEnabled(True)
        self.checkBox_writelog.setGeometry(QtCore.QRect(981, 259, 16, 16))
        self.checkBox_writelog.setMouseTracking(True)
        self.checkBox_writelog.setText("")
        self.checkBox_writelog.setTristate(False)
        self.checkBox_writelog.setObjectName("checkBox_writelog")
        self.pushButton_save = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_save.setGeometry(QtCore.QRect(520, 420, 75, 23))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_load = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_load.setGeometry(QtCore.QRect(520, 450, 75, 23))
        self.pushButton_load.setObjectName("pushButton_load")
        self.lineEdit_classstr.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.checkBox_nexttype.raise_()
        self.comboBox_urltype.raise_()
        self.checkBox_open.raise_()
        self.checkBox_next.raise_()
        self.checkBox_genLink.raise_()
        self.label_genLink.raise_()
        self.label_genLink_2.raise_()
        self.label_genLink_3.raise_()
        self.label_genLink_4.raise_()
        self.pushButton_find.raise_()
        self.checkBox_folderorfile.raise_()
        self.pushButton_rmvoidfolder.raise_()
        self.pushButton_renamefolder.raise_()
        self.pushButton_stop.raise_()
        self.pushButton_run.raise_()
        self.lineEdit_bspath.raise_()
        self.label_genLink_6.raise_()
        self.lineEdit_htmlstr.raise_()
        self.label_genLink_5.raise_()
        self.label_genLink_7.raise_()
        self.label_genLink_8.raise_()
        self.lineEdit_dbname.raise_()
        self.label_genLink_9.raise_()
        self.lineEdit_collection.raise_()
        self.lineEdit_modbkey.raise_()
        self.label_genLink_10.raise_()
        self.pushButton_writedb.raise_()
        self.comboBox_inserttype.raise_()
        self.label_genLink_11.raise_()
        self.label_genLink_12.raise_()
        self.checkBox_writelog.raise_()
        self.pushButton_save.raise_()
        self.pushButton_load.raise_()
        TpaUrlui.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(TpaUrlui)
        self.mainToolBar.setObjectName("mainToolBar")
        TpaUrlui.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(TpaUrlui)
        self.statusBar.setObjectName("statusBar")
        TpaUrlui.setStatusBar(self.statusBar)

        self.retranslateUi(TpaUrlui)
        QtCore.QMetaObject.connectSlotsByName(TpaUrlui)

    def retranslateUi(self, TpaUrlui):
        _translate = QtCore.QCoreApplication.translate
        TpaUrlui.setWindowTitle(_translate("TpaUrlui", "TpaUrlui"))
        self.label_filetype.setText(_translate("TpaUrlui", "文件类型：  "))
        self.comboBox_filetype.setItemText(0, _translate("TpaUrlui", "jpg"))
        self.comboBox_filetype.setItemText(1, _translate("TpaUrlui", "mp4"))
        self.label_filename.setText(_translate("TpaUrlui", "命名方式："))
        self.comboBox_filename.setItemText(0, _translate("TpaUrlui", "auto"))
        self.comboBox_srchtmclass.setItemText(0, _translate("TpaUrlui", "file"))
        self.comboBox_srchtmclass.setItemText(1, _translate("TpaUrlui", "a"))
        self.comboBox_srchtmclass.setItemText(2, _translate("TpaUrlui", "src"))
        self.label_srchtmclass.setText(_translate("TpaUrlui", "资源类型：    "))
        self.label_filesize.setText(_translate("TpaUrlui", "文件大小设定："))
        self.lineEdit_filesize.setText(_translate("TpaUrlui", "5000"))
        self.label_oldstr.setText(_translate("TpaUrlui", "原始字符串：  "))
        self.label_newstr.setText(_translate("TpaUrlui", "替换字符串："))
        self.label_url.setText(_translate("TpaUrlui", "网址：        "))
        self.label_type.setText(_translate("TpaUrlui", "类型："))
        self.lineEdit_type.setText(_translate("TpaUrlui", "open,down,next"))
        self.label_htmlpath.setText(_translate("TpaUrlui", "htmlpath："))
        self.label_baseurl.setText(_translate("TpaUrlui", "网址基地址：  "))
        self.label_filepath.setText(_translate("TpaUrlui", "存储文件夹："))
        self.lineEdit_filepath.setText(_translate("TpaUrlui", "E:\\"))
        self.label_times.setText(_translate("TpaUrlui", "页数：        "))
        self.lineEdit_times.setText(_translate("TpaUrlui", "1"))
        self.label_nextstr.setText(_translate("TpaUrlui", "下一页字符串："))
        self.comboBox_urltype.setItemText(0, _translate("TpaUrlui", "get"))
        self.comboBox_urltype.setItemText(1, _translate("TpaUrlui", "post"))
        self.label_genLink.setText(_translate("TpaUrlui", "生成链接文件："))
        self.label_genLink_2.setText(_translate("TpaUrlui", "文件类型"))
        self.label_genLink_3.setText(_translate("TpaUrlui", "使用字符串查找："))
        self.label_genLink_4.setText(_translate("TpaUrlui", "网址需基地址："))
        self.pushButton_find.setText(_translate("TpaUrlui", "查找"))
        self.pushButton_rmvoidfolder.setText(_translate("TpaUrlui", "文件夹整理"))
        self.pushButton_renamefolder.setText(_translate("TpaUrlui", "文件夹重命名"))
        self.pushButton_stop.setText(_translate("TpaUrlui", "停止"))
        self.pushButton_run.setText(_translate("TpaUrlui", "运行"))
        self.label_genLink_6.setText(_translate("TpaUrlui", "HTML路径："))
        self.label_genLink_5.setText(_translate("TpaUrlui", "路径字符串："))
        self.label_genLink_7.setText(_translate("TpaUrlui", "class名(可选)："))
        self.label_genLink_8.setText(_translate("TpaUrlui", "数据库名称："))
        self.label_genLink_9.setText(_translate("TpaUrlui", "collection名称："))
        self.label_genLink_10.setText(_translate("TpaUrlui", "Record键值："))
        self.pushButton_writedb.setText(_translate("TpaUrlui", "写入"))
        self.comboBox_inserttype.setItemText(0, _translate("TpaUrlui", "page"))
        self.comboBox_inserttype.setItemText(1, _translate("TpaUrlui", "key-value"))
        self.label_genLink_11.setText(_translate("TpaUrlui", "写入方式："))
        self.label_genLink_12.setText(_translate("TpaUrlui", "写入日志："))
        self.pushButton_save.setText(_translate("TpaUrlui", "保存"))
        self.pushButton_load.setText(_translate("TpaUrlui", "载入"))

