# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tpaurlui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TpaUrlui(object):
    def setupUi(self, TpaUrlui):
        TpaUrlui.setObjectName("TpaUrlui")
        TpaUrlui.resize(816, 430)
        self.centralWidget = QtWidgets.QWidget(TpaUrlui)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton_run = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_run.setGeometry(QtCore.QRect(700, 30, 75, 31))
        self.pushButton_run.setObjectName("pushButton_run")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(700, 70, 75, 31))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.label_srchtmclass = QtWidgets.QLabel(self.centralWidget)
        self.label_srchtmclass.setGeometry(QtCore.QRect(50, 370, 71, 20))
        self.label_srchtmclass.setObjectName("label_srchtmclass")
        self.label_filename = QtWidgets.QLabel(self.centralWidget)
        self.label_filename.setGeometry(QtCore.QRect(50, 320, 54, 20))
        self.label_filename.setObjectName("label_filename")
        self.label_filepath = QtWidgets.QLabel(self.centralWidget)
        self.label_filepath.setGeometry(QtCore.QRect(50, 270, 54, 20))
        self.label_filepath.setObjectName("label_filepath")
        self.label_filetype = QtWidgets.QLabel(self.centralWidget)
        self.label_filetype.setGeometry(QtCore.QRect(50, 220, 54, 20))
        self.label_filetype.setObjectName("label_filetype")
        self.label_baseurl = QtWidgets.QLabel(self.centralWidget)
        self.label_baseurl.setGeometry(QtCore.QRect(50, 170, 54, 20))
        self.label_baseurl.setObjectName("label_baseurl")
        self.label_htmlpath = QtWidgets.QLabel(self.centralWidget)
        self.label_htmlpath.setGeometry(QtCore.QRect(50, 120, 54, 20))
        self.label_htmlpath.setObjectName("label_htmlpath")
        self.label_type = QtWidgets.QLabel(self.centralWidget)
        self.label_type.setGeometry(QtCore.QRect(50, 70, 54, 20))
        self.label_type.setObjectName("label_type")
        self.label_url = QtWidgets.QLabel(self.centralWidget)
        self.label_url.setGeometry(QtCore.QRect(50, 20, 54, 20))
        self.label_url.setObjectName("label_url")
        self.lineEdit_srchtmclass = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_srchtmclass.setGeometry(QtCore.QRect(130, 370, 521, 20))
        self.lineEdit_srchtmclass.setObjectName("lineEdit_srchtmclass")
        self.lineEdit_filename = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_filename.setGeometry(QtCore.QRect(130, 320, 521, 20))
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_filepath.setGeometry(QtCore.QRect(130, 270, 521, 20))
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.lineEdit_filetype = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_filetype.setGeometry(QtCore.QRect(130, 220, 521, 20))
        self.lineEdit_filetype.setObjectName("lineEdit_filetype")
        self.lineEdit_baseurl = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_baseurl.setGeometry(QtCore.QRect(130, 170, 521, 20))
        self.lineEdit_baseurl.setObjectName("lineEdit_baseurl")
        self.lineEdit_htmlpath = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_htmlpath.setGeometry(QtCore.QRect(130, 120, 521, 20))
        self.lineEdit_htmlpath.setObjectName("lineEdit_htmlpath")
        self.lineEdit_type = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_type.setGeometry(QtCore.QRect(130, 70, 521, 20))
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.lineEdit_url = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_url.setGeometry(QtCore.QRect(130, 20, 521, 20))
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.pushButton_run.raise_()
        self.pushButton_stop.raise_()
        self.label_srchtmclass.raise_()
        self.label_filename.raise_()
        self.label_filepath.raise_()
        self.label_filetype.raise_()
        self.label_baseurl.raise_()
        self.label_htmlpath.raise_()
        self.label_type.raise_()
        self.label_url.raise_()
        self.lineEdit_srchtmclass.raise_()
        self.lineEdit_srchtmclass.raise_()
        self.lineEdit_srchtmclass.raise_()
        self.lineEdit_filename.raise_()
        self.lineEdit_filepath.raise_()
        self.lineEdit_filetype.raise_()
        self.lineEdit_baseurl.raise_()
        self.lineEdit_htmlpath.raise_()
        self.lineEdit_type.raise_()
        self.lineEdit_url.raise_()
        TpaUrlui.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(TpaUrlui)
        self.mainToolBar.setObjectName("mainToolBar")
        TpaUrlui.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(TpaUrlui)
        self.statusBar.setObjectName("statusBar")
        TpaUrlui.setStatusBar(self.statusBar)

        self.retranslateUi(TpaUrlui)
        QtCore.QMetaObject.connectSlotsByName(TpaUrlui)

    def retranslateUi(self, TpaUrlui):
        _translate = QtCore.QCoreApplication.translate
        TpaUrlui.setWindowTitle(_translate("TpaUrlui", "TpaUrlui"))
        self.pushButton_run.setText(_translate("TpaUrlui", "run"))
        self.pushButton_stop.setText(_translate("TpaUrlui", "stop"))
        self.label_srchtmclass.setText(_translate("TpaUrlui", "srchtmclass:"))
        self.label_filename.setText(_translate("TpaUrlui", "filename:"))
        self.label_filepath.setText(_translate("TpaUrlui", "filepath:"))
        self.label_filetype.setText(_translate("TpaUrlui", "filetype:"))
        self.label_baseurl.setText(_translate("TpaUrlui", "baseurl:"))
        self.label_htmlpath.setText(_translate("TpaUrlui", "htmlpath:"))
        self.label_type.setText(_translate("TpaUrlui", "type:"))
        self.label_url.setText(_translate("TpaUrlui", "url:"))