# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 652)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(980, 652))
        MainWindow.setMaximumSize(QtCore.QSize(980, 652))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 771, 601))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(100)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(240)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(240)
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(800, 10, 131, 601))
        self.layoutWidget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setBold(False)
        font.setWeight(50)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_camerafind = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_camerafind.setMinimumSize(QtCore.QSize(108, 30))
        self.pushButton_camerafind.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_camerafind.setFont(font)
        self.pushButton_camerafind.setObjectName("pushButton_camerafind")
        self.verticalLayout_2.addWidget(self.pushButton_camerafind)
        self.pushButton_merge = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_merge.setMinimumSize(QtCore.QSize(108, 30))
        self.pushButton_merge.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_merge.setFont(font)
        self.pushButton_merge.setObjectName("pushButton_merge")
        self.verticalLayout_2.addWidget(self.pushButton_merge)
        self.pushButton_dispnoconn = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_dispnoconn.setMinimumSize(QtCore.QSize(108, 30))
        self.pushButton_dispnoconn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_dispnoconn.setFont(font)
        self.pushButton_dispnoconn.setObjectName("pushButton_dispnoconn")
        self.verticalLayout_2.addWidget(self.pushButton_dispnoconn)
        self.pushButton_dispchange = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_dispchange.setMinimumSize(QtCore.QSize(108, 30))
        self.pushButton_dispchange.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_dispchange.setFont(font)
        self.pushButton_dispchange.setObjectName("pushButton_dispchange")
        self.verticalLayout_2.addWidget(self.pushButton_dispchange)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lineEdit_runstatus = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_runstatus.setMinimumSize(QtCore.QSize(108, 30))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineEdit_runstatus.setFont(font)
        self.lineEdit_runstatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_runstatus.setObjectName("lineEdit_runstatus")
        self.verticalLayout_2.addWidget(self.lineEdit_runstatus)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_load = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_load.setMinimumSize(QtCore.QSize(108, 30))
        self.pushButton_load.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setObjectName("pushButton_load")
        self.verticalLayout_4.addWidget(self.pushButton_load)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save.setMinimumSize(QtCore.QSize(108, 30))
        self.pushButton_save.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout_4.addWidget(self.pushButton_save)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setMinimumSize(QtCore.QSize(108, 30))
        self.pushButton_reset.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout.addWidget(self.pushButton_reset)
        self.pushButton_saveasinit = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_saveasinit.setMinimumSize(QtCore.QSize(108, 30))
        self.pushButton_saveasinit.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_saveasinit.setFont(font)
        self.pushButton_saveasinit.setObjectName("pushButton_saveasinit")
        self.verticalLayout.addWidget(self.pushButton_saveasinit)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "监控系统扫描工具"))
        self.pushButton_camerafind.setText(_translate("MainWindow", "摄像头扫描"))
        self.pushButton_merge.setText(_translate("MainWindow", "异常状态检测"))
        self.pushButton_dispnoconn.setText(_translate("MainWindow", "显示未连接设备"))
        self.pushButton_dispchange.setText(_translate("MainWindow", "显示已修改设备"))
        self.lineEdit_runstatus.setText(_translate("MainWindow", "欢迎使用"))
        self.pushButton_load.setText(_translate("MainWindow", "读取"))
        self.pushButton_save.setText(_translate("MainWindow", "保存"))
        self.pushButton_reset.setText(_translate("MainWindow", "重置至初始配置"))
        self.pushButton_saveasinit.setText(_translate("MainWindow", "设置为初始配置"))

