# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hist_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1030, 614)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.le_filename = QtWidgets.QLineEdit(Dialog)
        self.le_filename.setObjectName("le_filename")
        self.gridLayout.addWidget(self.le_filename, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 7, 1, 1)
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 3, 0, 1, 1)
        self.le_marknum = QtWidgets.QLineEdit(Dialog)
        self.le_marknum.setObjectName("le_marknum")
        self.gridLayout.addWidget(self.le_marknum, 1, 1, 1, 1)
        self.cb_fmt = QtWidgets.QComboBox(Dialog)
        self.cb_fmt.setObjectName("cb_fmt")
        self.cb_fmt.addItem("")
        self.cb_fmt.addItem("")
        self.cb_fmt.addItem("")
        self.cb_fmt.addItem("")
        self.gridLayout.addWidget(self.cb_fmt, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 7, 1, 1)
        self.btn_chooseFile = QtWidgets.QPushButton(Dialog)
        self.btn_chooseFile.setObjectName("btn_chooseFile")
        self.gridLayout.addWidget(self.btn_chooseFile, 0, 2, 1, 1)
        self.le_step_length = QtWidgets.QLineEdit(Dialog)
        self.le_step_length.setObjectName("le_step_length")
        self.gridLayout.addWidget(self.le_step_length, 0, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 0, 8, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.le_totalnum = QtWidgets.QLineEdit(Dialog)
        self.le_totalnum.setObjectName("le_totalnum")
        self.gridLayout.addWidget(self.le_totalnum, 1, 3, 1, 1)
        self.le_markrate = QtWidgets.QLineEdit(Dialog)
        self.le_markrate.setObjectName("le_markrate")
        self.gridLayout.addWidget(self.le_markrate, 1, 6, 1, 1)
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_getHistoryTgt = QtWidgets.QPushButton(self.tab)
        self.btn_getHistoryTgt.setObjectName("btn_getHistoryTgt")
        self.gridLayout_2.addWidget(self.btn_getHistoryTgt, 0, 0, 1, 1)
        self.btn_tgtsMark = QtWidgets.QPushButton(self.tab)
        self.btn_tgtsMark.setObjectName("btn_tgtsMark")
        self.gridLayout_2.addWidget(self.btn_tgtsMark, 0, 1, 1, 1)
        self.btn_tgtMark = QtWidgets.QPushButton(self.tab)
        self.btn_tgtMark.setObjectName("btn_tgtMark")
        self.gridLayout_2.addWidget(self.btn_tgtMark, 0, 2, 1, 1)
        self.tableView_trgt = QtWidgets.QTableView(self.tab)
        self.tableView_trgt.setObjectName("tableView_trgt")
        self.gridLayout_2.addWidget(self.tableView_trgt, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.le_rfmax = QtWidgets.QLineEdit(self.tab_2)
        self.le_rfmax.setObjectName("le_rfmax")
        self.gridLayout_3.addWidget(self.le_rfmax, 0, 4, 1, 1)
        self.le_doamin = QtWidgets.QLineEdit(self.tab_2)
        self.le_doamin.setObjectName("le_doamin")
        self.gridLayout_3.addWidget(self.le_doamin, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 2, 1, 1)
        self.le_primax = QtWidgets.QLineEdit(self.tab_2)
        self.le_primax.setObjectName("le_primax")
        self.gridLayout_3.addWidget(self.le_primax, 2, 4, 1, 1)
        self.le_primin = QtWidgets.QLineEdit(self.tab_2)
        self.le_primin.setObjectName("le_primin")
        self.gridLayout_3.addWidget(self.le_primin, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 4, 2, 1, 1)
        self.le_pamin = QtWidgets.QLineEdit(self.tab_2)
        self.le_pamin.setObjectName("le_pamin")
        self.gridLayout_3.addWidget(self.le_pamin, 4, 1, 1, 1)
        self.le_doamax = QtWidgets.QLineEdit(self.tab_2)
        self.le_doamax.setObjectName("le_doamax")
        self.gridLayout_3.addWidget(self.le_doamax, 3, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.le_rfmin = QtWidgets.QLineEdit(self.tab_2)
        self.le_rfmin.setObjectName("le_rfmin")
        self.gridLayout_3.addWidget(self.le_rfmin, 0, 1, 1, 1)
        self.le_pamax = QtWidgets.QLineEdit(self.tab_2)
        self.le_pamax.setObjectName("le_pamax")
        self.gridLayout_3.addWidget(self.le_pamax, 4, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 4, 0, 1, 1)
        self.le_pwmin = QtWidgets.QLineEdit(self.tab_2)
        self.le_pwmin.setObjectName("le_pwmin")
        self.gridLayout_3.addWidget(self.le_pwmin, 6, 1, 1, 1)
        self.le_pwmax = QtWidgets.QLineEdit(self.tab_2)
        self.le_pwmax.setObjectName("le_pwmax")
        self.gridLayout_3.addWidget(self.le_pwmax, 6, 4, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 6, 2, 1, 1)
        self.btn_mark = QtWidgets.QPushButton(self.tab_2)
        self.btn_mark.setObjectName("btn_mark")
        self.gridLayout_3.addWidget(self.btn_mark, 10, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 4, 0, 1, 8)
        self.cb_markMethod = QtWidgets.QComboBox(Dialog)
        self.cb_markMethod.setObjectName("cb_markMethod")
        self.cb_markMethod.addItem("")
        self.cb_markMethod.addItem("")
        self.gridLayout.addWidget(self.cb_markMethod, 3, 1, 1, 1)
        self.le_drfthr = QtWidgets.QLineEdit(Dialog)
        self.le_drfthr.setObjectName("le_drfthr")
        self.gridLayout.addWidget(self.le_drfthr, 2, 3, 1, 1)
        self.tableView_markRes = QtWidgets.QTableView(Dialog)
        self.tableView_markRes.setMinimumSize(QtCore.QSize(500, 0))
        self.tableView_markRes.setObjectName("tableView_markRes")
        self.gridLayout.addWidget(self.tableView_markRes, 1, 8, 5, 2)
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 2, 5, 1, 1)
        self.le_ddoathr = QtWidgets.QLineEdit(Dialog)
        self.le_ddoathr.setObjectName("le_ddoathr")
        self.gridLayout.addWidget(self.le_ddoathr, 2, 1, 1, 1)
        self.le_multi = QtWidgets.QLineEdit(Dialog)
        self.le_multi.setObjectName("le_multi")
        self.gridLayout.addWidget(self.le_multi, 2, 6, 1, 1)
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "历史信息及自定义标注"))
        self.label.setText(_translate("Dialog", "格式选择"))
        self.label_7.setText(_translate("Dialog", "%"))
        self.label_29.setText(_translate("Dialog", "标注方式"))
        self.cb_fmt.setItemText(0, _translate("Dialog", "xxgC"))
        self.cb_fmt.setItemText(1, _translate("Dialog", "STRU"))
        self.cb_fmt.setItemText(2, _translate("Dialog", "xD"))
        self.cb_fmt.setItemText(3, _translate("Dialog", "xxgZ"))
        self.label_2.setText(_translate("Dialog", "单步长度"))
        self.label_3.setText(_translate("Dialog", "ms"))
        self.btn_chooseFile.setText(_translate("Dialog", "选择文件"))
        self.le_step_length.setInputMask(_translate("Dialog", "0000000"))
        self.label_6.setText(_translate("Dialog", "标注率"))
        self.label_4.setText(_translate("Dialog", "标注数"))
        self.label_28.setText(_translate("Dialog", "标注结果"))
        self.label_5.setText(_translate("Dialog", "总数"))
        self.label_24.setText(_translate("Dialog", "dDOAThr"))
        self.btn_getHistoryTgt.setText(_translate("Dialog", "获取历史目标"))
        self.btn_tgtsMark.setText(_translate("Dialog", "目标表标注"))
        self.btn_tgtMark.setText(_translate("Dialog", "单目标标注"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "历史目标标注"))
        self.label_8.setText(_translate("Dialog", "RFmin"))
        self.le_doamin.setText(_translate("Dialog", "0"))
        self.label_12.setText(_translate("Dialog", "DOAmax"))
        self.label_9.setText(_translate("Dialog", "RFmax"))
        self.label_22.setText(_translate("Dialog", "PAmax"))
        self.le_pamin.setText(_translate("Dialog", "0"))
        self.le_doamax.setText(_translate("Dialog", "1024"))
        self.label_11.setText(_translate("Dialog", "PRImin"))
        self.label_10.setText(_translate("Dialog", "PRImax"))
        self.label_13.setText(_translate("Dialog", "DOAmin"))
        self.le_pamax.setText(_translate("Dialog", "3000"))
        self.label_14.setText(_translate("Dialog", "PWmin"))
        self.label_23.setText(_translate("Dialog", "PAmin"))
        self.le_pwmin.setText(_translate("Dialog", "0"))
        self.le_pwmax.setText(_translate("Dialog", "3000"))
        self.label_26.setText(_translate("Dialog", "PWmax"))
        self.btn_mark.setText(_translate("Dialog", "开始标注"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "自定义目标标注"))
        self.cb_markMethod.setItemText(0, _translate("Dialog", "单步标注"))
        self.cb_markMethod.setItemText(1, _translate("Dialog", "全部标注"))
        self.le_drfthr.setText(_translate("Dialog", "200"))
        self.label_25.setText(_translate("Dialog", "multi"))
        self.le_ddoathr.setText(_translate("Dialog", "10"))
        self.le_multi.setText(_translate("Dialog", "2"))
        self.label_27.setText(_translate("Dialog", "dRFThr"))

