# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tpaurlui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TpaUrlui(object):
    def setupUi(self, TpaUrlui):
        TpaUrlui.setObjectName("TpaUrlui")
        TpaUrlui.resize(692, 414)
        self.centralWidget = QtWidgets.QWidget(TpaUrlui)
        self.centralWidget.setObjectName("centralWidget")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 671, 361))
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(11, 0, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_baseurl = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_baseurl.setObjectName("lineEdit_baseurl")
        self.gridLayout.addWidget(self.lineEdit_baseurl, 3, 1, 1, 1)
        self.lineEdit_times = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_times.setObjectName("lineEdit_times")
        self.gridLayout.addWidget(self.lineEdit_times, 5, 1, 1, 1)
        self.label_baseurl = QtWidgets.QLabel(self.widget)
        self.label_baseurl.setObjectName("label_baseurl")
        self.gridLayout.addWidget(self.label_baseurl, 3, 0, 1, 1)
        self.lineEdit_htmlpath = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_htmlpath.setObjectName("lineEdit_htmlpath")
        self.gridLayout.addWidget(self.lineEdit_htmlpath, 2, 1, 1, 1)
        self.label_times = QtWidgets.QLabel(self.widget)
        self.label_times.setObjectName("label_times")
        self.gridLayout.addWidget(self.label_times, 5, 0, 1, 1)
        self.label_type = QtWidgets.QLabel(self.widget)
        self.label_type.setObjectName("label_type")
        self.gridLayout.addWidget(self.label_type, 1, 0, 1, 1)
        self.label_url = QtWidgets.QLabel(self.widget)
        self.label_url.setObjectName("label_url")
        self.gridLayout.addWidget(self.label_url, 0, 0, 1, 1)
        self.lineEdit_url = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.gridLayout.addWidget(self.lineEdit_url, 0, 1, 1, 1)
        self.label_filepath = QtWidgets.QLabel(self.widget)
        self.label_filepath.setObjectName("label_filepath")
        self.gridLayout.addWidget(self.label_filepath, 4, 0, 1, 1)
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.gridLayout.addWidget(self.lineEdit_filepath, 4, 1, 1, 1)
        self.lineEdit_type = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_type.setClearButtonEnabled(False)
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.gridLayout.addWidget(self.lineEdit_type, 1, 1, 1, 1)
        self.label_htmlpath = QtWidgets.QLabel(self.widget)
        self.label_htmlpath.setObjectName("label_htmlpath")
        self.gridLayout.addWidget(self.label_htmlpath, 2, 0, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 9)
        self.gridLayout.setColumnMinimumWidth(1, 9)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_srchtmclass = QtWidgets.QLabel(self.widget)
        self.label_srchtmclass.setObjectName("label_srchtmclass")
        self.gridLayout_2.addWidget(self.label_srchtmclass, 2, 0, 1, 1)
        self.comboBox_filetype = QtWidgets.QComboBox(self.widget)
        self.comboBox_filetype.setObjectName("comboBox_filetype")
        self.comboBox_filetype.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_filetype, 0, 1, 1, 1)
        self.label_filename = QtWidgets.QLabel(self.widget)
        self.label_filename.setObjectName("label_filename")
        self.gridLayout_2.addWidget(self.label_filename, 1, 0, 1, 1)
        self.label_filetype = QtWidgets.QLabel(self.widget)
        self.label_filetype.setObjectName("label_filetype")
        self.gridLayout_2.addWidget(self.label_filetype, 0, 0, 1, 1)
        self.comboBox_filename = QtWidgets.QComboBox(self.widget)
        self.comboBox_filename.setObjectName("comboBox_filename")
        self.comboBox_filename.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_filename, 1, 1, 1, 1)
        self.comboBox_srchtmclass = QtWidgets.QComboBox(self.widget)
        self.comboBox_srchtmclass.setObjectName("comboBox_srchtmclass")
        self.comboBox_srchtmclass.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_srchtmclass, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton_run = QtWidgets.QPushButton(self.widget)
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout_3.addWidget(self.pushButton_run, 0, 1, 1, 1)
        self.pushButton_stop = QtWidgets.QPushButton(self.widget)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout_3.addWidget(self.pushButton_stop, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_filesize = QtWidgets.QLabel(self.widget)
        self.label_filesize.setObjectName("label_filesize")
        self.gridLayout_4.addWidget(self.label_filesize, 0, 0, 1, 1)
        self.lineEdit_filesize = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_filesize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_filesize.setObjectName("lineEdit_filesize")
        self.gridLayout_4.addWidget(self.lineEdit_filesize, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 2, 1, 1)
        self.pushButton_rmvoidfolder = QtWidgets.QPushButton(self.widget)
        self.pushButton_rmvoidfolder.setObjectName("pushButton_rmvoidfolder")
        self.gridLayout_4.addWidget(self.pushButton_rmvoidfolder, 0, 3, 1, 1)
        self.label_oldstr = QtWidgets.QLabel(self.widget)
        self.label_oldstr.setObjectName("label_oldstr")
        self.gridLayout_4.addWidget(self.label_oldstr, 1, 0, 1, 1)
        self.lineEdit_oldstr = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_oldstr.setObjectName("lineEdit_oldstr")
        self.gridLayout_4.addWidget(self.lineEdit_oldstr, 1, 1, 1, 1)
        self.pushButton_renamefolder = QtWidgets.QPushButton(self.widget)
        self.pushButton_renamefolder.setObjectName("pushButton_renamefolder")
        self.gridLayout_4.addWidget(self.pushButton_renamefolder, 1, 3, 1, 1)
        self.label_newstr = QtWidgets.QLabel(self.widget)
        self.label_newstr.setObjectName("label_newstr")
        self.gridLayout_4.addWidget(self.label_newstr, 2, 0, 1, 1)
        self.lineEdit_newstr = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_newstr.setObjectName("lineEdit_newstr")
        self.gridLayout_4.addWidget(self.lineEdit_newstr, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 0, 1, 2)
        TpaUrlui.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(TpaUrlui)
        self.mainToolBar.setObjectName("mainToolBar")
        TpaUrlui.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(TpaUrlui)
        self.statusBar.setObjectName("statusBar")
        TpaUrlui.setStatusBar(self.statusBar)

        self.retranslateUi(TpaUrlui)
        QtCore.QMetaObject.connectSlotsByName(TpaUrlui)

    def retranslateUi(self, TpaUrlui):
        _translate = QtCore.QCoreApplication.translate
        TpaUrlui.setWindowTitle(_translate("TpaUrlui", "TpaUrlui"))
        self.lineEdit_times.setText(_translate("TpaUrlui", "1"))
        self.label_baseurl.setText(_translate("TpaUrlui", "网址基地址："))
        self.label_times.setText(_translate("TpaUrlui", "页数：        "))
        self.label_type.setText(_translate("TpaUrlui", "类型："))
        self.label_url.setText(_translate("TpaUrlui", "网址："))
        self.label_filepath.setText(_translate("TpaUrlui", "存储文件夹："))
        self.lineEdit_filepath.setText(_translate("TpaUrlui", "E:\\"))
        self.lineEdit_type.setText(_translate("TpaUrlui", "open,down,next"))
        self.label_htmlpath.setText(_translate("TpaUrlui", "htmlpath："))
        self.label_srchtmclass.setText(_translate("TpaUrlui", "资源类型：    "))
        self.comboBox_filetype.setItemText(0, _translate("TpaUrlui", "jpg"))
        self.label_filename.setText(_translate("TpaUrlui", "命名方式："))
        self.label_filetype.setText(_translate("TpaUrlui", "文件类型：  "))
        self.comboBox_filename.setItemText(0, _translate("TpaUrlui", "auto"))
        self.comboBox_srchtmclass.setItemText(0, _translate("TpaUrlui", "file"))
        self.pushButton_run.setText(_translate("TpaUrlui", "运行"))
        self.pushButton_stop.setText(_translate("TpaUrlui", "停止"))
        self.label_filesize.setText(_translate("TpaUrlui", "文件大小设定："))
        self.lineEdit_filesize.setText(_translate("TpaUrlui", "5000"))
        self.pushButton_rmvoidfolder.setText(_translate("TpaUrlui", "文件夹整理"))
        self.label_oldstr.setText(_translate("TpaUrlui", "原始字符串："))
        self.pushButton_renamefolder.setText(_translate("TpaUrlui", "文件夹重命名"))
        self.label_newstr.setText(_translate("TpaUrlui", "替换字符串："))

