# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tpaurlui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TpaUrlui(object):
    def setupUi(self, TpaUrlui):
        TpaUrlui.setObjectName("TpaUrlui")
        TpaUrlui.resize(786, 532)
        self.centralWidget = QtWidgets.QWidget(TpaUrlui)
        self.centralWidget.setObjectName("centralWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 250, 142, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_filetype = QtWidgets.QLabel(self.layoutWidget)
        self.label_filetype.setObjectName("label_filetype")
        self.gridLayout_2.addWidget(self.label_filetype, 0, 0, 1, 1)
        self.comboBox_filetype = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_filetype.setObjectName("comboBox_filetype")
        self.comboBox_filetype.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_filetype, 0, 1, 1, 1)
        self.label_filename = QtWidgets.QLabel(self.layoutWidget)
        self.label_filename.setObjectName("label_filename")
        self.gridLayout_2.addWidget(self.label_filename, 1, 0, 1, 1)
        self.comboBox_filename = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_filename.setObjectName("comboBox_filename")
        self.comboBox_filename.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_filename, 1, 1, 1, 1)
        self.label_srchtmclass = QtWidgets.QLabel(self.layoutWidget)
        self.label_srchtmclass.setObjectName("label_srchtmclass")
        self.gridLayout_2.addWidget(self.label_srchtmclass, 2, 0, 1, 1)
        self.comboBox_srchtmclass = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_srchtmclass.setObjectName("comboBox_srchtmclass")
        self.comboBox_srchtmclass.addItem("")
        self.comboBox_srchtmclass.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_srchtmclass, 2, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(690, 250, 82, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_run = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_run.setObjectName("pushButton_run")
        self.verticalLayout.addWidget(self.pushButton_run)
        self.pushButton_stop = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout.addWidget(self.pushButton_stop)
        self.pushButton_rmvoidfolder = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_rmvoidfolder.setObjectName("pushButton_rmvoidfolder")
        self.verticalLayout.addWidget(self.pushButton_rmvoidfolder)
        self.pushButton_renamefolder = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_renamefolder.setObjectName("pushButton_renamefolder")
        self.verticalLayout.addWidget(self.pushButton_renamefolder)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(13, 340, 651, 121))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_filesize = QtWidgets.QLabel(self.layoutWidget2)
        self.label_filesize.setObjectName("label_filesize")
        self.gridLayout_3.addWidget(self.label_filesize, 0, 0, 1, 1)
        self.lineEdit_filesize = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_filesize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_filesize.setObjectName("lineEdit_filesize")
        self.gridLayout_3.addWidget(self.lineEdit_filesize, 0, 1, 1, 1)
        self.label_oldstr = QtWidgets.QLabel(self.layoutWidget2)
        self.label_oldstr.setObjectName("label_oldstr")
        self.gridLayout_3.addWidget(self.label_oldstr, 1, 0, 1, 1)
        self.lineEdit_oldstr = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_oldstr.setObjectName("lineEdit_oldstr")
        self.gridLayout_3.addWidget(self.lineEdit_oldstr, 1, 1, 1, 1)
        self.label_newstr = QtWidgets.QLabel(self.layoutWidget2)
        self.label_newstr.setObjectName("label_newstr")
        self.gridLayout_3.addWidget(self.label_newstr, 2, 0, 1, 1)
        self.lineEdit_newstr = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_newstr.setObjectName("lineEdit_newstr")
        self.gridLayout_3.addWidget(self.lineEdit_newstr, 2, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 671, 241))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_url = QtWidgets.QLabel(self.layoutWidget3)
        self.label_url.setObjectName("label_url")
        self.gridLayout.addWidget(self.label_url, 0, 0, 1, 1)
        self.lineEdit_url = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_url.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_url.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_url.setText("")
        self.lineEdit_url.setClearButtonEnabled(False)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.gridLayout.addWidget(self.lineEdit_url, 0, 1, 1, 1)
        self.label_type = QtWidgets.QLabel(self.layoutWidget3)
        self.label_type.setObjectName("label_type")
        self.gridLayout.addWidget(self.label_type, 1, 0, 1, 1)
        self.lineEdit_type = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_type.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_type.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_type.setClearButtonEnabled(False)
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.gridLayout.addWidget(self.lineEdit_type, 1, 1, 1, 1)
        self.label_htmlpath = QtWidgets.QLabel(self.layoutWidget3)
        self.label_htmlpath.setObjectName("label_htmlpath")
        self.gridLayout.addWidget(self.label_htmlpath, 2, 0, 1, 1)
        self.lineEdit_htmlpath = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_htmlpath.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_htmlpath.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_htmlpath.setObjectName("lineEdit_htmlpath")
        self.gridLayout.addWidget(self.lineEdit_htmlpath, 2, 1, 1, 1)
        self.label_baseurl = QtWidgets.QLabel(self.layoutWidget3)
        self.label_baseurl.setObjectName("label_baseurl")
        self.gridLayout.addWidget(self.label_baseurl, 3, 0, 1, 1)
        self.lineEdit_baseurl = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_baseurl.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_baseurl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_baseurl.setObjectName("lineEdit_baseurl")
        self.gridLayout.addWidget(self.lineEdit_baseurl, 3, 1, 1, 1)
        self.label_filepath = QtWidgets.QLabel(self.layoutWidget3)
        self.label_filepath.setObjectName("label_filepath")
        self.gridLayout.addWidget(self.label_filepath, 4, 0, 1, 1)
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_filepath.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_filepath.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.gridLayout.addWidget(self.lineEdit_filepath, 4, 1, 1, 1)
        self.label_times = QtWidgets.QLabel(self.layoutWidget3)
        self.label_times.setObjectName("label_times")
        self.gridLayout.addWidget(self.label_times, 5, 0, 1, 1)
        self.lineEdit_times = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_times.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_times.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_times.setObjectName("lineEdit_times")
        self.gridLayout.addWidget(self.lineEdit_times, 5, 1, 1, 1)
        self.label_nextstr = QtWidgets.QLabel(self.layoutWidget3)
        self.label_nextstr.setObjectName("label_nextstr")
        self.gridLayout.addWidget(self.label_nextstr, 6, 0, 1, 1)
        self.lineEdit_nextstr = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_nextstr.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_nextstr.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_nextstr.setText("")
        self.lineEdit_nextstr.setObjectName("lineEdit_nextstr")
        self.gridLayout.addWidget(self.lineEdit_nextstr, 6, 1, 1, 1)
        self.checkBox_nexttype = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_nexttype.setGeometry(QtCore.QRect(691, 220, 16, 16))
        self.checkBox_nexttype.setText("")
        self.checkBox_nexttype.setObjectName("checkBox_nexttype")
        self.comboBox_urltype = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_urltype.setGeometry(QtCore.QRect(690, 20, 50, 20))
        self.comboBox_urltype.setObjectName("comboBox_urltype")
        self.comboBox_urltype.addItem("")
        self.comboBox_urltype.addItem("")
        self.checkBox_open = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_open.setGeometry(QtCore.QRect(691, 121, 16, 16))
        self.checkBox_open.setText("")
        self.checkBox_open.setObjectName("checkBox_open")
        self.checkBox_next = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_next.setGeometry(QtCore.QRect(710, 121, 16, 16))
        self.checkBox_next.setText("")
        self.checkBox_next.setObjectName("checkBox_next")
        TpaUrlui.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(TpaUrlui)
        self.mainToolBar.setObjectName("mainToolBar")
        TpaUrlui.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(TpaUrlui)
        self.statusBar.setObjectName("statusBar")
        TpaUrlui.setStatusBar(self.statusBar)

        self.retranslateUi(TpaUrlui)
        QtCore.QMetaObject.connectSlotsByName(TpaUrlui)

    def retranslateUi(self, TpaUrlui):
        _translate = QtCore.QCoreApplication.translate
        TpaUrlui.setWindowTitle(_translate("TpaUrlui", "TpaUrlui"))
        self.label_filetype.setText(_translate("TpaUrlui", "文件类型：  "))
        self.comboBox_filetype.setItemText(0, _translate("TpaUrlui", "jpg"))
        self.label_filename.setText(_translate("TpaUrlui", "命名方式："))
        self.comboBox_filename.setItemText(0, _translate("TpaUrlui", "auto"))
        self.label_srchtmclass.setText(_translate("TpaUrlui", "资源类型：    "))
        self.comboBox_srchtmclass.setItemText(0, _translate("TpaUrlui", "file"))
        self.comboBox_srchtmclass.setItemText(1, _translate("TpaUrlui", "src"))
        self.pushButton_run.setText(_translate("TpaUrlui", "运行"))
        self.pushButton_stop.setText(_translate("TpaUrlui", "停止"))
        self.pushButton_rmvoidfolder.setText(_translate("TpaUrlui", "文件夹整理"))
        self.pushButton_renamefolder.setText(_translate("TpaUrlui", "文件夹重命名"))
        self.label_filesize.setText(_translate("TpaUrlui", "文件大小设定："))
        self.lineEdit_filesize.setText(_translate("TpaUrlui", "5000"))
        self.label_oldstr.setText(_translate("TpaUrlui", "原始字符串：  "))
        self.label_newstr.setText(_translate("TpaUrlui", "替换字符串："))
        self.label_url.setText(_translate("TpaUrlui", "网址：        "))
        self.label_type.setText(_translate("TpaUrlui", "类型："))
        self.lineEdit_type.setText(_translate("TpaUrlui", "open,down,next"))
        self.label_htmlpath.setText(_translate("TpaUrlui", "htmlpath："))
        self.label_baseurl.setText(_translate("TpaUrlui", "网址基地址：  "))
        self.label_filepath.setText(_translate("TpaUrlui", "存储文件夹："))
        self.lineEdit_filepath.setText(_translate("TpaUrlui", "E:\\"))
        self.label_times.setText(_translate("TpaUrlui", "页数：        "))
        self.lineEdit_times.setText(_translate("TpaUrlui", "1"))
        self.label_nextstr.setText(_translate("TpaUrlui", "下一页字符串："))
        self.comboBox_urltype.setItemText(0, _translate("TpaUrlui", "get"))
        self.comboBox_urltype.setItemText(1, _translate("TpaUrlui", "post"))

